ChildImmunizationSystem/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('fault/<str:msg>/', views.fault, name='fault'),
    path('success/<str:msg>/', views.success, name='success'),
    path('send-notifications/', views.send_notifications, name='send_notifications'),
    path('populate/', views.populate, name='populate'),
    path('account/', include('account.urls')),
    path('beneficiary/', include('beneficiary.urls')),
    path('medical/', include('medical.urls')),
    path('location/', include('location.urls')),
    path('data/', include('data.urls')),
]

data/urls.py
from django.urls import path

from . import views

app_name = 'data'

urlpatterns = [
]

medical/urls.py
from django.urls import path

from . import views

app_name = 'medical'

urlpatterns = [
    path('list-children/', views.list_children, name='list_children'),    
    path('detail-children/<int:pk>/', views.detail_children, name='detail_children'),
    path('toggle-child-vaccination-status/<int:pk>/', views.toggle_child_vaccination_status, name='toggle_child_vaccination_status'),
    path('list-children-medical-helper/', views.list_children_medical_helper, name='list_children_medical_helper'),    
    path('detail-children-medical-helper/<int:pk>/', views.detail_children_medical_helper, name='detail_children_medical_helper'),
    path('medical-agency-analysis-locality-wise/', views.medical_agency_analysis_locality_wise, name='medical_agency_analysis_locality_wise'),
    path('medical-agency-analysis-parent-wise/<int:pk>/', views.medical_agency_analysis_parent_wise, name='medical_agency_analysis_parent_wise'),
    path('district-medical-officer-analysis-locality-wise/', views.district_medical_officer_analysis_locality_wise, name='district_medical_officer_analysis_locality_wise'),   
    path('district-medical-officer-analysis-parent-wise/<int:pk>/', views.district_medical_officer_analysis_parent_wise, name='district_medical_officer_analysis_parent_wise'),
    path('state-medical-officer-analysis-district-wise/', views.state_medical_officer_analysis_district_wise, name='state_medical_officer_analysis_district_wise'),
    path('state-medical-officer-analysis-locality-wise/<int:pk>/', views.state_medical_officer_analysis_locality_wise, name='state_medical_officer_analysis_locality_wise'),
    path('state-medical-officer-analysis-parent-wise/<int:pk>/', views.state_medical_officer_analysis_parent_wise, name='state_medical_officer_analysis_parent_wise'),
    path('add-healthcare-policy/', views.add_healthcare_policy, name='add_healthcare_policy'),
    path('list-healthcare-policy/', views.list_healthcare_policy, name='list_healthcare_policy'),
    path('detail-healthcare-policy/<int:pk>/', views.detail_healthcare_policy, name='detail_healthcare_policy'),
]

medical/models.py
from django.db import models
from django.contrib import auth

# Create your models here.

class StateMedicalOfficer(models.Model):
    user = models.ForeignKey(auth.models.User, related_name='state_medical_officers', on_delete=models.CASCADE)
    state = models.ForeignKey('location.State', related_name='state_medical_officers', on_delete=models.CASCADE)
    
    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'

    class Meta():
        verbose_name_plural = 'State Medical Officers'


class DistrictMedicalOfficer(models.Model):
    user = models.ForeignKey(auth.models.User, related_name='district_medical_officers', on_delete=models.CASCADE)
    district = models.ForeignKey('location.District', related_name='district_medical_officers', on_delete=models.CASCADE)
    
    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'

    class Meta():
        verbose_name_plural = 'District Medical Officers'


class MedicalAgency(models.Model):
    user = models.ForeignKey(auth.models.User, related_name='medical_agencies', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    
    def __str__(self):
        return f'{self.name}'

    class Meta():
        verbose_name_plural = 'Medical Agencies'


class MedicalHelper(models.Model):
    user = models.ForeignKey(auth.models.User, related_name='medical_helpers', on_delete=models.CASCADE)
    medical_agency = models.ForeignKey('medical.MedicalAgency', related_name='medical_helpers', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.medical_agency} -- {self.user.first_name} {self.user.last_name}'

    class Meta():
        verbose_name_plural = 'Medical Helpers'


class HealthcarePolicy(models.Model):
    state = models.ForeignKey('location.State', related_name='healthcare_policies', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField()
    eligibility = models.TextField()
    process = models.TextField()

    def __str__(self):
        return f'{self.state} -- {self.title}'

    class Meta():
        verbose_name_plural = 'Healthcare Policies'

     

medical/forms.py
from django import forms
from location import models as loc_models
from . import models

class GetParentUsernameForm(forms.Form):
    parent_username = forms.CharField()


class AddHealthcarePolicyForm(forms.ModelForm):

    class Meta():
        model = models.HealthcarePolicy
        exclude = ['state']


class GetStateForm(forms.Form):
    state = forms.ChoiceField(choices=[])

    def __init__(self, *args, **kwargs):
        super(GetStateForm, self).__init__(*args, **kwargs)

        STATE_CHOICES = [(None, '---Select---')]

        state_list = loc_models.State.objects.all()
        for state in state_list:
            STATE_CHOICES.append((state.pk, state.__str__()))


        self.fields['state'] = forms.ChoiceField(choices=STATE_CHOICES)

medical/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail

from beneficiary import models as ben_models
from location import models as loc_models

from . import models, forms

import datetime, json
# Create your views here.

@login_required
def list_children(request):
    if request.method == 'POST':
        form = forms.GetParentUsernameForm(data=request.POST)
        if form.is_valid():
            parent_username = form.cleaned_data['parent_username']

            try:
                parent = ben_models.Parent.objects.get(user__username__exact=parent_username)
            except:
                return redirect('fault', msg='Invalid Username entered')
            if parent.locality.medical_agency.user.pk == request.user.pk:
                children_list = parent.children.all()
                form = forms.GetParentUsernameForm()
                return render(request, 'medical/list-children.html', {'children_list':children_list, 'form': form}) 
            else:
                return redirect('fault', msg='The given parent does not reside in your area of operation')
        else:
            return redirect('fault', msg='Invalid Request')
    else:
        form = forms.GetParentUsernameForm()
        return render(request, 'medical/list-children.html', {'form':form})


@login_required
def detail_children(request, pk):
    child = ben_models.Child.objects.get(pk__exact=pk)
    if request.user.pk == child.parent.locality.medical_agency.user.pk:
        vaccination_status_list = child.child_vaccines.all()
        return render(request, 'medical/detail-children.html', {'vaccination_status_list':vaccination_status_list})
    else:
        return redirect('fault', msg='ACCESS DENIED!')


@login_required
def toggle_child_vaccination_status(request, pk):
    child_vaccine = ben_models.ChildVaccine.objects.get(pk__exact=pk)
    child = child_vaccine.child
    if request.user.pk == child.parent.locality.medical_agency.user.pk:
        child_vaccine.is_vaccinated = not(child_vaccine.is_vaccinated)
        child_vaccine.save()
        vaccination_status_list = child.child_vaccines.all()
        return render(request, 'medical/detail-children.html', {'vaccination_status_list':vaccination_status_list})
    else:
        return redirect('fault', msg='ACCESS DENIED!')


@login_required
def list_children_medical_helper(request):
    if request.method == 'POST':
        form = forms.GetParentUsernameForm(data=request.POST)
        if form.is_valid():
            parent_username = form.cleaned_data['parent_username']

            try:
                parent = ben_models.Parent.objects.get(user__username__exact=parent_username)
            except:
                return redirect('fault', msg='Invalid Username entered')
            if parent.medical_helper.user.pk == request.user.pk:
                children_list = parent.children.all()
                form = forms.GetParentUsernameForm()
                return render(request, 'medical/list-children-medical-helper.html', {'children_list':children_list, 'form': form}) 
            else:
                return redirect('fault', msg='The given parent does not reside in your area of operation')
        else:
            return redirect('fault', msg='Invalid Request')
    else:
        form = forms.GetParentUsernameForm()
        return render(request, 'medical/list-children-medical-helper.html', {'form':form})


@login_required
def detail_children_medical_helper(request, pk):
    child = ben_models.Child.objects.get(pk__exact=pk)
    if child.parent.medical_helper.user.pk == request.user.pk:
        vaccination_status_list = child.child_vaccines.all()
        return render(request, 'medical/detail-children-medical-helper.html', {'vaccination_status_list':vaccination_status_list})
    else:
        return redirect('fault', msg='ACCESS DENIED!')


@login_required
def medical_agency_analysis_locality_wise(request):
    medical_agency = models.MedicalAgency.objects.get(user__pk__exact=request.user.pk)
    locality_list = medical_agency.localities.all()
    locality_wise_vaccination_status = []
    label = []
    value = []
    for locality in locality_list:
        vaccination_done_count = vaccination_missed_count = 0
        parents = locality.parents.all()
        for parent in parents:
            children = parent.children.all()
            for child in children:
                vaccination_done_count += ben_models.ChildVaccine.objects.all().filter(child__exact=child, scheduled_date__lte=datetime.date.today(), is_vaccinated__exact=True).count()
                vaccination_missed_count += ben_models.ChildVaccine.objects.all().filter(child__exact=child, scheduled_date__lte=datetime.date.today(), is_vaccinated__exact=False).count()
        if (vaccination_done_count + vaccination_missed_count) > 0:
            vaccinated_percentage = round((vaccination_done_count/(vaccination_done_count + vaccination_missed_count))*100, 2)
        else:
            vaccinated_percentage = 0
        label.append(locality.name)
        value.append(vaccinated_percentage)
        locality_wise_vaccination_status.append({'locality_pk':locality.pk, 'locality_name':locality.name, 'vaccination_done_count':vaccination_done_count, 'vaccination_missed_count':vaccination_missed_count, 'vaccinated_percentage':vaccinated_percentage})
    data = { "label": label, "value": value}
    jsondata = json.dumps(data)
    return render(request, 'medical/medical-agency-analysis-locality-wise.html', {'locality_wise_vaccination_status':locality_wise_vaccination_status, 'jsondata':jsondata})


@login_required
def medical_agency_analysis_parent_wise(request, pk):
    locality = loc_models.Locality.objects.get(pk__exact=pk)
    parents = locality.parents.all()
    parent_wise_vaccination_status = []
    label = []
    value = []
    for parent in parents:
        vaccination_done_count = vaccination_missed_count = 0
        children = parent.children.all()
        for child in children:
            vaccination_done_count += ben_models.ChildVaccine.objects.all().filter(child__exact=child, scheduled_date__lte=datetime.date.today(), is_vaccinated__exact=True).count()
            vaccination_missed_count += ben_models.ChildVaccine.objects.all().filter(child__exact=child, scheduled_date__lte=datetime.date.today(), is_vaccinated__exact=False).count()
        if (vaccination_done_count + vaccination_missed_count) > 0:
            vaccinated_percentage = round((vaccination_done_count/(vaccination_done_count + vaccination_missed_count))*100, 2)
        else:
            vaccinated_percentage = 0
        label.append(f'{parent.user.first_name} {parent.user.last_name}')
        value.append(vaccinated_percentage)
        parent_wise_vaccination_status.append({'parent_pk':parent.pk, 'parent_name':f'{parent.user.first_name} {parent.user.last_name}', 'vaccination_done_count':vaccination_done_count, 'vaccination_missed_count':vaccination_missed_count, 'vaccinated_percentage':vaccinated_percentage})
    data = { "label": label, "value": value}
    jsondata = json.dumps(data)
    return render(request, 'medical/medical-agency-analysis-parent-wise.html', {'parent_wise_vaccination_status':parent_wise_vaccination_status, 'jsondata':jsondata})


@login_required
def district_medical_officer_analysis_locality_wise(request):
    district_medical_officer = models.DistrictMedicalOfficer.objects.get(user__pk__exact=request.user.pk)
    district = district_medical_officer.district
    locality_list = district.localities.all()
    locality_wise_vaccination_status = []
    label = []
    value = []
    for locality in locality_list:
        vaccination_done_count = vaccination_missed_count = 0
        parents = locality.parents.all()
        for parent in parents:
            children = parent.children.all()
            for child in children:
                vaccination_done_count += ben_models.ChildVaccine.objects.all().filter(child__exact=child, scheduled_date__lte=datetime.date.today(), is_vaccinated__exact=True).count()
                vaccination_missed_count += ben_models.ChildVaccine.objects.all().filter(child__exact=child, scheduled_date__lte=datetime.date.today(), is_vaccinated__exact=False).count()
        if (vaccination_done_count + vaccination_missed_count) > 0:
            vaccinated_percentage = round((vaccination_done_count/(vaccination_done_count + vaccination_missed_count))*100, 2)
        else:
            vaccinated_percentage = 0
        label.append(locality.name)
        value.append(vaccinated_percentage)
        locality_wise_vaccination_status.append({'locality_pk':locality.pk, 'locality_name':locality.name, 'vaccination_done_count':vaccination_done_count, 'vaccination_missed_count':vaccination_missed_count, 'vaccinated_percentage':vaccinated_percentage})
    data = { "label": label, "value": value}
    jsondata = json.dumps(data)
    return render(request, 'medical/district-medical-officer-analysis-locality-wise.html', {'locality_wise_vaccination_status':locality_wise_vaccination_status, 'jsondata':jsondata})     


@login_required
def district_medical_officer_analysis_parent_wise(request, pk):
    locality = loc_models.Locality.objects.get(pk__exact=pk)
    parents = locality.parents.all()
    parent_wise_vaccination_status = []
    label = []
    value = []
    for parent in parents:
        vaccination_done_count = vaccination_missed_count = 0
        children = parent.children.all()
        for child in children:
            vaccination_done_count += ben_models.ChildVaccine.objects.all().filter(child__exact=child, scheduled_date__lte=datetime.date.today(), is_vaccinated__exact=True).count()
            vaccination_missed_count += ben_models.ChildVaccine.objects.all().filter(child__exact=child, scheduled_date__lte=datetime.date.today(), is_vaccinated__exact=False).count()

medical/templates/medical/_charts.html
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.js"></script>
<div class="container-custom">
    <br>
    <canvas id="myChart" width="30" height="20" style="background-color:#e8f5e9;"></canvas>
</div>
<script>
    var ctx = document.getElementById("myChart").getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'horizontalBar',
        data: {
            labels: jsonobject.label,
            datasets: [{
                label: '% of Vaccination Successful',
                data: jsonobject.value,
                backgroundColor: [
                    'rgba(41, 182, 246, 0.5)',
                    'rgba(149, 117, 205, 0.5)',
                    'rgba(239, 154, 154, 0.5)',
                    'rgba(255, 213, 79, 0.5)',
                    'rgba(57, 73, 171, 0.5)',
                    'rgba(165, 214, 167, 0.5)',
                    'rgba(255, 167, 38, 0.5)',
                    'rgba(41, 182, 246, 0.5)',
                    'rgba(149, 117, 205, 0.5)',
                    'rgba(239, 154, 154, 0.5)',
                    'rgba(255, 213, 79, 0.5)',
                    'rgba(57, 73, 171, 0.5)',
                    'rgba(165, 214, 167, 0.5)',
                    'rgba(255, 167, 38, 0.5)',
                ],
                borderColor: [
                    'rgba(41, 182, 246, 1)',
                    'rgba(149, 117, 205, 1)',
                    'rgba(239, 154, 154, 1)',
                    'rgba(255, 213, 79, 1)',
                    'rgba(57, 73, 171, 1)',
                    'rgba(165, 214, 167, 1)',
                    'rgba(255, 167, 38, 1)',
                    'rgba(41, 182, 246, 1)',
                    'rgba(149, 117, 205, 1)',
                    'rgba(239, 154, 154, 1)',
                    'rgba(255, 213, 79, 1)',
                    'rgba(57, 73, 171, 1)',
                    'rgba(165, 214, 167, 1)',
                    'rgba(255, 167, 38, 1)',
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    stacked:true,
                    ticks: {
                        beginAtZero: true,
                    }
                }],
                xAxes: [{
                    stacked:true,
                    ticks: {
                        beginAtZero: true,
                        suggestedMax: 100
                    }
                }]
            }
        }
    });
</script>

medical/templates/medical/detail-children.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}
    Vaccination Status List | Child Immunization System
{% endblock page_title %}

{% block content %}
    <center>
        <h3><strong>Vaccination Status List</strong></h3>
    </center>
    <table class="highlight centered responsive-table">
        <thead>
            <tr>
                <th>S. No.</th>
                <th>Vaccine</th>
                <th>Scheduled Date</th>
                <th>Vaccination Status</th>
                <th>Toggle Status</th>
            </tr>
        </thead>
        <tbody>
            {% for child_vcc in vaccination_status_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ child_vcc.vaccine }}</td>
                    <td>{{ child_vcc.scheduled_date }}</td>
                    <td>
                        {% if child_vcc.is_vaccinated %}
                            <i class="material-icons green-text">check_circle</i>
                        {% else %}
                            <i class="material-icons red-text">cancel</i>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{% url 'medical:toggle_child_vaccination_status' pk=child_vcc.pk %}" class="waves-effect waves-light btn">Toggle</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

medical/templates/medical/district-medical-officer-analysis-locality-wise.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}
    Vaccination Status Analysis | Child Immunization System
{% endblock page_title %}

{% block content %}
    <script>
        var jsonobject = JSON.parse('{{ jsondata | escapejs }}');
    </script>
    <div class="row">
        <div class="col s10">
            <h3>Vaccination Status Analysis</h3>
        </div>
        <div class="col s2" style="padding-top: 2.5em;">
            <a class="waves-effect waves-light btn modal-trigger" href="#chart"><i class="material-icons">insert_chart</i></a>
        </div>
    </div>

    <div id="chart" class="modal modal-fixed-footer green lighten-5">
        {% include "medical/_charts.html" %}
    </div>


    <table class="highlight centered responsive-table">
        <thead>
            <tr>
                <th>S. No.</th>
                <th>Locality Name</th>
                <th>Successful Vaccination Count</th>
                <th>Unsuccessful Vaccination Count</th>
                <th>Vaccination Percentage</th>
            </tr>
        </thead>
        <tbody>
            {% for locality_status in locality_wise_vaccination_status %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'medical:district_medical_officer_analysis_parent_wise' pk=locality_status.locality_pk %}"><strong>{{ locality_status.locality_name }}</strong></a></td>
                    <td>{{ locality_status.vaccination_done_count }}</td>
                    <td>{{ locality_status.vaccination_missed_count }}</td>
                    <td>{{ locality_status.vaccinated_percentage }} %</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

medical/templates/medical/list-children-medical-helper.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}
    Children List | Child Immunization System
{% endblock page_title %}

{% block content %}
    <h3>Get Children List</h3>
    <form method="POST">
        {% csrf_token %}
        <div class="input-field">
            {{ form.parent_username }}
            <label for="parent_username">Parent Username</label>
        </div>
        <button class="waves-effect waves-light btn">Get Details</button>
    </form>
    <br><br>

    <table class="highlight centered responsive-table">
        <thead>
            <tr>
                <th>S. No.</th>
                <th>First Name</th>
                <th>Last Name</th>
            </tr>
        </thead>
        <tbody>
            {% for child in children_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'medical:detail_children_medical_helper' pk=child.pk %}">{{ child.first_name }}</a></td>
                    <td><a href="{% url 'medical:detail_children_medical_helper' pk=child.pk %}">{{ child.last_name }}</a></td>
                </tr>
            {% empty %}
                <tr>
                    <td><i class="material-icons">remove</i></td>
                    <td><i class="material-icons">remove</i></td>
                    <td><i class="material-icons">remove</i></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

medical/templates/medical/list-children.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}
    Children List | Child Immunization System
{% endblock page_title %}

{% block content %}
    <center>
        <strong><h3>Get Children List</h3></strong>
    </center>
    <br>
    <form method="POST">
        {% csrf_token %}
        <div class="input-field">
            {{ form.parent_username }}
            <label for="parent_username">Parent Username</label>
        </div>
        <button class="waves-effect waves-light btn">Get Details</button>
    </form>
    <br><br>

    <table class="highlight centered responsive-table">
        <thead>
            <tr>
                <th>S. No.</th>
                <th>First Name</th>
                <th>Last Name</th>
            </tr>
        </thead>
        <tbody>
            {% for child in children_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'medical:detail_children' pk=child.pk %}">{{ child.first_name }}</a></td>
                    <td><a href="{% url 'medical:detail_children' pk=child.pk %}">{{ child.last_name }}</a></td>
                </tr>
            {% empty %}
                <tr>
                    <td><i class="material-icons">remove</i></td>
                    <td><i class="material-icons">remove</i></td>
                    <td><i class="material-icons">remove</i></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

medical/templates/medical/list-healthcare-policy.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}
	Healthcare Policy List | Child Immunization System
{% endblock page_title %}


{% block content %}
	<center>
		<h3><strong>Healthcare Policy List</strong></h3>
	</center>
	<br>
	<form method="POST">
		{% csrf_token %}
		<div class="input-field">
			{{ form.state }}
			<label for="state">State of Residence</label>
		</div>
		<button class="waves-effect waves-light btn">Get Details</button>
	</form>
	<br><br>

	{% for healthcare_policy in healthcare_policy_list %}
		<div class="row">
			<div class="col s12 m12">
				<div class="card teal">
					<div class="card-content white-text">
						<span class="card-title"><strong>{{ healthcare_policy.title }}</strong></span>
						<br>
						<p style="text-align: justify;">{{ healthcare_policy.description|truncatechars:350 }}</p>
					</div>
					<div class="card-action">
						<a href="{% url 'medical:detail_healthcare_policy' pk=healthcare_policy.pk %}"><u
								class="white-text">LEARN MORE...</u></a>
					</div>
				</div>
			</div>
		</div>
	{% endfor %}


{% endblock content %}

medical/templates/medical/medical-agency-analysis-locality-wise.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}
    Vaccination Status Analysis | Child Immunization System
{% endblock page_title %}

{% block content %}
    <script>
        var jsonobject = JSON.parse('{{ jsondata | escapejs }}');
    </script>
    <div class="row">
        <div class="col s10">
            <h3>Vaccination Status Analysis</h3>
        </div>
        <div class="col s2" style="padding-top: 2.5em;">
            <a class="waves-effect waves-light btn modal-trigger" href="#chart"><i class="material-icons">insert_chart</i></a>
        </div>
    </div>

    <div id="chart" class="modal modal-fixed-footer green lighten-5">
        {% include "medical/_charts.html" %}
    </div>


    <table class="highlight centered responsive-table">
        <thead>
            <tr>
                <th>S. No.</th>
                <th>Locality Name</th>
                <th>Successful Vaccination Count</th>
                <th>Unsuccessful Vaccination Count</th>
                <th>Vaccination Percentage</th>
            </tr>
        </thead>
        <tbody>
            {% for locality_status in locality_wise_vaccination_status %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'medical:medical_agency_analysis_parent_wise' pk=locality_status.locality_pk %}"><strong>{{ locality_status.locality_name }}</strong></a></td>
                    <td>{{ locality_status.vaccination_done_count }}</td>
                    <td>{{ locality_status.vaccination_missed_count }}</td>
                    <td>{{ locality_status.vaccinated_percentage }} %</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

medical/templates/medical/state-medical-officer-analysis-district-wise.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}
    Vaccination Status Analysis | Child Immunization System
{% endblock page_title %}

{% block content %}
    <script>
        var jsonobject = JSON.parse('{{ jsondata | escapejs }}');
    </script>
    <div class="row">
        <div class="col s10">
            <h3>Vaccination Status Analysis</h3>
        </div>
        <div class="col s2" style="padding-top: 2.5em;">
            <a class="waves-effect waves-light btn modal-trigger" href="#chart"><i class="material-icons">insert_chart</i></a>
        </div>
    </div>

    <div id="chart" class="modal modal-fixed-footer green lighten-5">
        {% include "medical/_charts.html" %}
    </div>


    <table class="highlight centered responsive-table">
        <thead>
            <tr>
                <th>S. No.</th>
                <th>District Name</th>
                <th>Successful Vaccination Count</th>
                <th>Unsuccessful Vaccination Count</th>
                <th>Vaccination Percentage</th>
            </tr>
        </thead>
        <tbody>
            {% for district_status in district_wise_vaccination_status %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'medical:state_medical_officer_analysis_locality_wise' pk=district_status.district_pk %}"><strong>{{ district_status.district_name }}</strong></a></td>
                    <td>{{ district_status.vaccination_done_count }}</td>
                    <td>{{ district_status.vaccination_missed_count }}</td>
                    <td>{{ district_status.vaccinated_percentage }} %</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

medical/templates/medical/state-medical-officer-analysis-locality-wise.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}
    Vaccination Status Analysis | Child Immunization System
{% endblock page_title %}


{% block content %}
    <script>
        var jsonobject = JSON.parse('{{ jsondata | escapejs }}');
    </script>
    <!-- <h3>Vaccination Status Analysis<a class="waves-effect waves-light btn modal-trigger" href="#chart"><i class="material-icons">insert_chart</i></a></h3> -->

    <div class="row">
        <div class="col s10">
            <h3>Vaccination Status Analysis</h3>
        </div>
        <div class="col s2" style="padding-top: 2.5em;">
            <a class="waves-effect waves-light btn modal-trigger" href="#chart"><i class="material-icons">insert_chart</i></a>
        </div>
    </div>
    

    <div id="chart" class="modal modal-fixed-footer green lighten-5">
        {% include "medical/_charts.html" %}
    </div>


    <table class="highlight centered responsive-table">
        <thead>
            <tr>
                <th>S. No.</th>
                <th>Locality Name</th>
                <th>Successful Vaccination Count</th>
                <th>Unsuccessful Vaccination Count</th>
                <th>Vaccination Percentage</th>
            </tr>
        </thead>
        <tbody>
            {% for locality_status in locality_wise_vaccination_status %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'medical:state_medical_officer_analysis_parent_wise' pk=locality_status.locality_pk %}"><strong>{{ locality_status.locality_name }}</strong></a></td>
                    <td>{{ locality_status.vaccination_done_count }}</td>
                    <td>{{ locality_status.vaccination_missed_count }}</td>
                    <td>{{ locality_status.vaccinated_percentage }} %</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}