ChildImmunizationSystem/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('fault/<str:msg>/', views.fault, name='fault'),
    path('success/<str:msg>/', views.success, name='success'),
    path('send-notifications/', views.send_notifications, name='send_notifications'),
    path('populate/', views.populate, name='populate'),
    path('account/', include('account.urls')),
    path('beneficiary/', include('beneficiary.urls')),
    path('medical/', include('medical.urls')),
    path('location/', include('location.urls')),
    path('data/', include('data.urls')),
]

account/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth import views as auth_views

from . import views

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', csrf_protect(auth_views.LogoutView.as_view()), name='logout'),
]

beneficiary/urls.py
from django.urls import path

from . import views

app_name = 'beneficiary'

urlpatterns = [
    path('signup-parent/', views.signup_parent, name='signup_parent'),
    path('create-parent/', views.create_parent, name='create_parent'),
    path('add-child-to-parent/', views.add_child_to_parent, name='add_child_to_parent'),
    path('list-children/<int:pk>/', views.list_children, name='list_children'),
    path('detail-children/<int:pk>/', views.detail_children, name='detail_children'),
    path('detail-medical/<int:pk>/', views.detail_medical, name='detail_medical'),
]

data/urls.py
from django.urls import path

from . import views

app_name = 'data'

urlpatterns = [
]

medical/urls.py
from django.urls import path

from . import views

app_name = 'medical'

urlpatterns = [
    path('list-children/', views.list_children, name='list_children'),    
    path('detail-children/<int:pk>/', views.detail_children, name='detail_children'),
    path('toggle-child-vaccination-status/<int:pk>/', views.toggle_child_vaccination_status, name='toggle_child_vaccination_status'),
    path('list-children-medical-helper/', views.list_children_medical_helper, name='list_children_medical_helper'),    
    path('detail-children-medical-helper/<int:pk>/', views.detail_children_medical_helper, name='detail_children_medical_helper'),
    path('medical-agency-analysis-locality-wise/', views.medical_agency_analysis_locality_wise, name='medical_agency_analysis_locality_wise'),
    path('medical-agency-analysis-parent-wise/<int:pk>/', views.medical_agency_analysis_parent_wise, name='medical_agency_analysis_parent_wise'),
    path('district-medical-officer-analysis-locality-wise/', views.district_medical_officer_analysis_locality_wise, name='district_medical_officer_analysis_locality_wise'),   
    path('district-medical-officer-analysis-parent-wise/<int:pk>/', views.district_medical_officer_analysis_parent_wise, name='district_medical_officer_analysis_parent_wise'),
    path('state-medical-officer-analysis-district-wise/', views.state_medical_officer_analysis_district_wise, name='state_medical_officer_analysis_district_wise'),
    path('state-medical-officer-analysis-locality-wise/<int:pk>/', views.state_medical_officer_analysis_locality_wise, name='state_medical_officer_analysis_locality_wise'),
    path('state-medical-officer-analysis-parent-wise/<int:pk>/', views.state_medical_officer_analysis_parent_wise, name='state_medical_officer_analysis_parent_wise'),
    path('add-healthcare-policy/', views.add_healthcare_policy, name='add_healthcare_policy'),
    path('list-healthcare-policy/', views.list_healthcare_policy, name='list_healthcare_policy'),
    path('detail-healthcare-policy/<int:pk>/', views.detail_healthcare_policy, name='detail_healthcare_policy'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            {% block page_title %}
                Child Immunization System
            {% endblock page_title %}
        </title>

        <link rel="icon" type="image/png" href="{% static 'images/logo.png' %}"/>

        <!-- Compiled and minified jQuery -->
        <!-- <script src="https://code.jquery.com/jquery-3.5.0.min.js" integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script> -->
        <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>

        <!-- Materialize Compiled and minified CSS -->
        <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"> -->
        <link rel="stylesheet" href="{% static 'materialize/css/materialize.min.css' %}">

        <!-- Materialize Icons -->
        <!-- <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> -->
        <link rel="stylesheet" href="{% static 'materialize/css/icon.css' %}">

        <!-- Materialize Compiled and minified JavaScript -->
        <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script> -->
        <script src="{% static 'materialize/js/materialize.min.js' %}"></script>

        {% block head %}
        {% endblock head %}

        <style>
            #register_child_dropdown>li:hover {
                background-color: #006064 ;
            }
            .container-custom {
                margin: 0 auto;
                max-width: 1280px;
                width: 90%;
            }
        </style>

    </head>
    <body class="green lighten-5">


        <ul id="register_child_dropdown" class="dropdown-content cyan darken-3">
            <li><a href="{% url 'beneficiary:create_parent' %}" class="teal-text text-lighten-5">New Parent</a></li>
            <li><a href="{% url 'beneficiary:add_child_to_parent' %}" class="teal-text text-lighten-5">Existing parent</a></li>
        </ul>
        
        <ul class="sidenav cyan darken-4" id="mobile-nav">
            {% if user.is_authenticated %}
                <li><a href="#!"><strong class="white-text">Hello, {{ user.first_name }} {{ user.last_name }}</strong></a></li>
                {% if user.pk in parent_users %}
                    <li><a href="{% url 'beneficiary:list_children' pk=user.pk %}" class="teal-text text-lighten-5">My Children</a></li>
                    <li><a href="{% url 'beneficiary:detail_medical' pk=user.pk %}" class="teal-text text-lighten-5">Get Medical Help</a></li>
                {% endif %}
                {% if user.pk in medical_agency_users %}
                    <li><a class="dropdown-trigger" href="#!" data-target="register_child_dropdown">Register Child<i class="material-icons right">arrow_drop_down</i></a></li>
                    <li><a href="{% url 'medical:list_children' %}" class="teal-text text-lighten-5">View Parent Details</a></li>
                    <li><a href="{% url 'medical:medical_agency_analysis_locality_wise' %}" class="teal-text text-lighten-5">Locality Wise Analysis</a></li>
                {% endif %}
                {% if user.pk in medical_helper_users %}
                    <li><a href="{% url 'medical:list_children_medical_helper' %}" class="teal-text text-lighten-5">View Parent Details</a></li>
                {% endif %}
                {% if user.pk in district_medical_officer_users %}
                    <li><a href="{% url 'medical:district_medical_officer_analysis_locality_wise' %}" class="teal-text text-lighten-5">Locality Wise Analysis</a></li>
                {% endif %}
                {% if user.pk in state_medical_officer_users %}
                    <li><a href="{% url 'medical:state_medical_officer_analysis_district_wise' %}" class="teal-text text-lighten-5">District Wise Analysis</a></li>
                    <li><a href="{% url 'medical:add_healthcare_policy' %}" class="teal-text text-lighten-5">Add Healthcare Policy</a></li>
                {% endif %}
                <li><a href="{% url 'medical:list_healthcare_policy' %}" class="teal-text text-lighten-5">Healthcare Policies</a></li>
                <li><a href="{% url 'account:logout' %}" class="teal-text text-lighten-5">Logout</a></li>
            {% else %}
                <li><a href="{% url 'medical:list_healthcare_policy' %}" class="teal-text text-lighten-5">Healthcare Policies</a></li>
                <li style="border-left: #004d40 5px solid;"><a href="{% url 'account:login' %}" class="teal-text text-lighten-5">Login</a></li>
            {% endif %}
        </ul>

        <div class="navbar-fixed">
            <nav>
                <div class="nav-wrapper cyan darken-4">
                    <a href="{% url 'home' %}" class="left brand-logo"><img src="{% static 'images/logo.png' %}" width="50" height="auto" style="margin-left: 20px;"></a>
                    <a href="{% url 'home' %}" class="brand-logo hide-on-med-and-down" style="margin-left: 80px;">&nbsp;Child Immunization System</a>
                    <a href="#" data-target="mobile-nav" class="right sidenav-trigger"><i class="material-icons">menu</i></a>
                    <ul class="right hide-on-med-and-down">
                        {% if user.is_authenticated %}
                            <li><a href="#!"><strong>Hello, {{ user.first_name }} {{ user.last_name }}</strong></a></li>
                            {% if user.pk in parent_users %}
                                <li><a href="{% url 'beneficiary:list_children' pk=user.pk %}" class="teal-text text-lighten-5">My Children</a></li>
                                <li><a href="{% url 'beneficiary:detail_medical' pk=user.pk %}" class="teal-text text-lighten-5">Get Medical Help</a></li>
                            {% endif %}
                            {% if user.pk in medical_agency_users %}
                                <li><a class="dropdown-trigger" href="#!" data-target="register_child_dropdown">Register Child<i class="material-icons right">arrow_drop_down</i></a></li>
                                <li><a href="{% url 'medical:list_children' %}" class="teal-text text-lighten-5">View Parent Details</a></li>
                                <li><a href="{% url 'medical:medical_agency_analysis_locality_wise' %}" class="teal-text text-lighten-5">Locality Wise Analysis</a></li>
                            {% endif %}
                            {% if user.pk in medical_helper_users %}
                                <li><a href="{% url 'medical:list_children_medical_helper' %}" class="teal-text text-lighten-5">View Parent Details</a></li>
                            {% endif %}
                            {% if user.pk in district_medical_officer_users %}
                                <li><a href="{% url 'medical:district_medical_officer_analysis_locality_wise' %}" class="teal-text text-lighten-5">Locality Wise Analysis</a></li>
                            {% endif %}
                            {% if user.pk in state_medical_officer_users %}
                                <li><a href="{% url 'medical:state_medical_officer_analysis_district_wise' %}" class="teal-text text-lighten-5">District Wise Analysis</a></li>
                                <li><a href="{% url 'medical:add_healthcare_policy' %}" class="teal-text text-lighten-5">Add Healthcare Policy</a></li>
                            {% endif %}
                            <li><a href="{% url 'medical:list_healthcare_policy' %}" class="teal-text text-lighten-5">Healthcare Policies</a></li>
                            <li style="border-left: #004d40 5px solid;">
                                <a href="#" onclick="document.getElementById('logout-form').submit();" class="teal-text text-lighten-5">Logout</a>
                                <form id="logout-form" method="post" action="{% url 'account:logout' %}" style="display: none;">
                                    {% csrf_token %}
                                </form>
                            </li>
                        {% else %}
                            <li><a href="{% url 'medical:list_healthcare_policy' %}" class="teal-text text-lighten-5">Healthcare Policies</a></li>
                            <li style="border-left: #004d40 5px solid;"><a href="{% url 'account:login' %}" class="teal-text text-lighten-5">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </div>

        <div class="container-custom">
            {% block content %}
            {% endblock content %}
        </div>

        {% block tail %}
        {% endblock tail %}

        <br><br><br>

        <script>
            $(document).ready(function(){
                $('select').formSelect();
            });

            $(document).ready(function(){
                $('.datepicker').datepicker({
                    format: "yyyy-mm-dd"
                });
            });

            $(document).ready(function () {
                $('.modal').modal();
            });

            $(document).ready(function () {
                $(".dropdown-trigger").dropdown();            
            });

            $(document).ready(function(){
                $('.sidenav').sidenav();
            });
        </script>
    </body>
</html>

templates/fault.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}
    Fault | Child Immunization System
{% endblock page_title %}

{% block content %}
    <div class="container">
        <br><br><br>
        <div class="row">
            <div class="col s3 m3 l3"></div>
            <div class="col s6 m6 l6">
                <div class="card blue-grey lighten-4 center">
                    <div class="card-content">
                        <span class="card-title"><b>Error Encountered</b></span>
                        <p>{{msg}}</p>
                    </div>
                </div>
            </div>
            <div class="col s3 m3 l3"></div>
        </div>
    </div>
{% endblock content %}

templates/home.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}
Home | Child Immunization System
{% endblock page_title %}

{% block head %}
	<style>
		.card-heading {
			margin: 0;
		}
		.card-content {
			padding: 0.5em !important;
		}
	</style>
{% endblock head %}

{% block content %}
	<script>
		var jsonobject = JSON.parse('{{ jsondata | escapejs }}');
	</script>

	<br>

	<div class="row">
		<div class="col l9 m12 s12">
			<center>
				<img src="{% static 'images/home-image-1.png' %}" width="80%" height="auto">
			</center>
			<br><br><br>
			<div class="row">
				<div class="col l6 m12 s12">
					{% include "charts/_pie_total_charts.html" %}
				</div>
				<div class="col l6 m12 s12">
					{% include "charts/_pie_vcc_charts.html" %}
				</div>
			</div>
		</div>
		<div class="col l3 m12 s12">
			<br><br><br>
			<div class="row">
				<div class="col s12">
					<div class="card cyan darken-2">
						<div class="card-content white-text">
							<h4 class="card-heading">{{ children_count }}</h4>
							<h6>Children Registered</h6>
						</div>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col s12">
					<div class="card cyan darken-2">
						<div class="card-content white-text">
							<h4 class="card-heading">{{ parent_count }}</h4>
							<h6>Active Parents</h6>
						</div>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col s12">
					<div class="card cyan darken-2">
						<div class="card-content white-text">
							<h4 class="card-heading">{{ medical_agency_count }}</h4>
							<h6>Medical Agencies Partnered</h6>
						</div>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col s12">
					<div class="card cyan darken-2">
						<div class="card-content white-text">
							<h4 class="card-heading">{{ locality_count }}</h4>
							<h6>Localities Covered</h6>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>


	<br><br><br><br><br><br>
	<div class="row">
		<div class="col l8 s12">
			{% include "charts/_line_charts.html" %}
		</div>
		<div class="col l4 s12">
			<br><br>
			<img src="{% static 'images/home-image-2.png' %}">
		</div>
	</div>
	<br><br><br><br><br>
	<div class="row">
		<div class="col l4 s12">
			<br><br><br>
			<img src="{% static 'images/home-image-3.png' %}" width="100%" height="auto">
		</div>
		<div class="col l8 s12">
			{% include "charts/_bar_charts.html" %}
		</div>
	</div>


{% endblock content %}

templates/success.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}
    Success | Child Immunization System
{% endblock page_title %}

{% block content %}
    <div class="container">
        <br><br><br>
        <div class="row">
            <div class="col s3 m3 l3"></div>
            <div class="col s6 m6 l6">
                <div class="card green lighten-4 center">
                    <div class="card-content">
                        <span class="card-title"><b>Task Successful</b></span>
                        <p>{{msg}}</p>
                    </div>
                </div>
            </div>
            <div class="col s3 m3 l3"></div>
        </div>
    </div>
{% endblock content %}